// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Drug struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32                `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Power                int32                `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Drug) Reset()         { *m = Drug{} }
func (m *Drug) String() string { return proto.CompactTextString(m) }
func (*Drug) ProtoMessage()    {}
func (*Drug) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Drug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Drug.Unmarshal(m, b)
}
func (m *Drug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Drug.Marshal(b, m, deterministic)
}
func (m *Drug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Drug.Merge(m, src)
}
func (m *Drug) XXX_Size() int {
	return xxx_messageInfo_Drug.Size(m)
}
func (m *Drug) XXX_DiscardUnknown() {
	xxx_messageInfo_Drug.DiscardUnknown(m)
}

var xxx_messageInfo_Drug proto.InternalMessageInfo

func (m *Drug) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Drug) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Drug) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Drug) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *Drug) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Drug)(nil), "proto.drug")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0xce, 0x82, 0x30,
	0x14, 0x46, 0x53, 0x7e, 0xfa, 0x47, 0xae, 0xd1, 0xa1, 0x71, 0x68, 0x58, 0x24, 0x4e, 0x4c, 0x25,
	0xd1, 0xc9, 0xd1, 0x57, 0x20, 0xee, 0xa6, 0xd0, 0x2b, 0x69, 0x22, 0x14, 0xcb, 0x45, 0xe3, 0x93,
	0xf8, 0xba, 0x26, 0x45, 0x9c, 0xee, 0x3d, 0xf9, 0xce, 0x70, 0x60, 0x35, 0xa0, 0x7f, 0xd8, 0x1a,
	0x55, 0xef, 0x1d, 0x39, 0xc1, 0xc3, 0x49, 0xb7, 0x8d, 0x73, 0xcd, 0x0d, 0x8b, 0x40, 0xd5, 0x78,
	0x2d, 0xc8, 0xb6, 0x38, 0x90, 0x6e, 0xfb, 0xc9, 0xdb, 0xbd, 0x19, 0xc4, 0xc6, 0x8f, 0x8d, 0x58,
	0x43, 0x64, 0x8d, 0x64, 0x19, 0xcb, 0x79, 0x19, 0x59, 0x23, 0x04, 0xc4, 0x9d, 0x6e, 0x51, 0x46,
	0x19, 0xcb, 0x93, 0x32, 0xfc, 0x22, 0x85, 0xc5, 0x7d, 0xd4, 0x1d, 0x59, 0x7a, 0xc9, 0xbf, 0x60,
	0xfe, 0x58, 0x6c, 0x80, 0xf7, 0xee, 0x89, 0x5e, 0xc6, 0x61, 0x98, 0x40, 0x1c, 0x01, 0x6a, 0x8f,
	0x9a, 0xd0, 0x5c, 0x34, 0x49, 0x9e, 0xb1, 0x7c, 0xb9, 0x4f, 0xd5, 0x14, 0xa5, 0xe6, 0x28, 0x75,
	0x9e, 0xa3, 0xca, 0xe4, 0x6b, 0x9f, 0xa8, 0xfa, 0x0f, 0xf3, 0xe1, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x35, 0x3c, 0x6b, 0xa1, 0xd9, 0x00, 0x00, 0x00,
}
